### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by artoniaz** [xpwmaosldk/number_pagination#1]
Useful, but styling on mobile is terrible. Can't handle too small numer buttons while control buttons remain huge.

**Comment by xpwmaosldk** [comment]
Thanks for first issue.
I will fix that soon :)

**Comment by xpwmaosldk** [comment]
I'm planing to offer a variety of custom styles, but it seems unlikely that they will be applied in the near future.
Instead, you can use the fontSize to change number buttons size.

<img width="695" alt="스크린샷 2022-03-11 오전 11 22 58" src="https://user-images.githubusercontent.com/13146337/157790546-989fef25-c536-4948-bf2e-5a56cea79bff.png">
